language: ruby

rvm:
  - 2.2.4
  - 2.3.1
  - ruby-head


cache: bundler
bundler_args: --jobs=4 --retry=3
sudo: false


before_script:
  - bundle exec appraisal install


script:
  - 'bundle exec appraisal rspec'
